-- Realtime + SLA + audit/notification support for FixMyCity.

begin;

-- SLA columns on issues.
alter table public.issues
  add column if not exists resolved_at timestamptz,
  add column if not exists sla_due_at timestamptz;

-- Ensure every issue has a due time target (48h default).
update public.issues
set sla_due_at = created_at + interval '48 hours'
where sla_due_at is null;

create or replace function public.set_issue_sla_fields()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    if new.sla_due_at is null then
      new.sla_due_at = new.created_at + interval '48 hours';
    end if;
  end if;

  if tg_op = 'UPDATE' then
    if old.status is distinct from new.status
       and new.status = 'resolved'::public.issue_status
       and new.resolved_at is null then
      new.resolved_at = now();
    end if;

    if old.status = 'resolved'::public.issue_status
       and new.status <> 'resolved'::public.issue_status then
      new.resolved_at = null;
    end if;

    if new.sla_due_at is null then
      new.sla_due_at = coalesce(new.created_at, old.created_at) + interval '48 hours';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_set_issue_sla_fields on public.issues;
create trigger trg_set_issue_sla_fields
before insert or update on public.issues
for each row
execute function public.set_issue_sla_fields();

-- Audit table for admin actions.
create table if not exists public.issue_logs (
  id bigint generated by default as identity primary key,
  issue_id text not null references public.issues(id) on delete cascade,
  action text not null,
  user_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_issue_logs_issue_id_created_at
  on public.issue_logs(issue_id, created_at desc);

alter table public.issue_logs enable row level security;

-- Admins can read and write issue logs.
drop policy if exists "admins read issue logs" on public.issue_logs;
create policy "admins read issue logs"
on public.issue_logs
for select
to authenticated
using (
  exists (
    select 1 from public.admins a where a.user_id = auth.uid()
  )
);

drop policy if exists "admins insert issue logs" on public.issue_logs;
create policy "admins insert issue logs"
on public.issue_logs
for insert
to authenticated
with check (
  exists (
    select 1 from public.admins a where a.user_id = auth.uid()
  )
);

-- Queue table for email/push integrations (Edge Functions worker target).
create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  issue_id text not null references public.issues(id) on delete cascade,
  event_type text not null,
  actor_user_id uuid references auth.users(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  status text not null default 'pending'
);

create index if not exists idx_notification_events_pending
  on public.notification_events(status, created_at)
  where processed_at is null;

alter table public.notification_events enable row level security;

drop policy if exists "admins read notification events" on public.notification_events;
create policy "admins read notification events"
on public.notification_events
for select
to authenticated
using (
  exists (
    select 1 from public.admins a where a.user_id = auth.uid()
  )
);

drop policy if exists "admins insert notification events" on public.notification_events;
create policy "admins insert notification events"
on public.notification_events
for insert
to authenticated
with check (
  exists (
    select 1 from public.admins a where a.user_id = auth.uid()
  )
);

commit;
